name: Cypress Tests with Allure Report

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code về
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Cài dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Chạy Cypress tests
      - name: Run Cypress tests
        run: npm run test

      # 5. Generate Allure Report
      - name: Generate Allure Report
        run: npm run allure:generate

      # 6. Deploy Allure Report lên GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }} # Dùng token bạn vừa tạo
          publish_dir: ./allure-report
          publish_branch: gh-pages
